definitions:
  dto.CreateOrganizationRequest:
    properties:
      email:
        type: string
      organization_name:
        type: string
      password:
        minLength: 8
        type: string
      phone_number:
        type: string
      registered_name:
        type: string
      website_url:
        type: string
    required:
    - email
    - organization_name
    - password
    - phone_number
    - registered_name
    type: object
  dto.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  dto.OrganizationLoginResponse:
    properties:
      api_key:
        type: string
      email:
        type: string
      id:
        type: string
      organization_name:
        type: string
      phone_number:
        type: string
      registered_name:
        type: string
    type: object
  dto.OrganizationSignupResponse:
    properties:
      api_key:
        type: string
      api_secret:
        type: string
      email:
        type: string
      id:
        type: string
      organization_name:
        type: string
      phone_number:
        type: string
      registered_name:
        type: string
    type: object
info:
  contact:
    email: osundemichael7@gmail.com
    name: API Support
    url: https://github.com/michaelkinginfosec
  description: A Ledger-as-a-Service API. Platforms integrate Vaultex to manage their
    users' wallets and track every financial transaction via double-entry bookkeeping.
  title: Vaultex
  version: "1.0"
paths:
  /organizations:
    post:
      consumes:
      - application/json
      description: Create a new organization with the provided name and email
      parameters:
      - description: Organization data
        in: body
        name: organization
        required: true
        schema:
          $ref: '#/definitions/dto.CreateOrganizationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.OrganizationSignupResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Create a new organization
      tags:
      - Auth
  /organizations/email/{email}:
    get:
      consumes:
      - application/json
      description: Retrieve an organization by their email address
      parameters:
      - description: Organization Email
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.OrganizationLoginResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get organization by email
      tags:
      - organizations
  /organizations/login:
    post:
      consumes:
      - application/json
      description: Authenticate an organization using their email and password
      parameters:
      - description: Login credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.OrganizationLoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Login an organization
      tags:
      - Auth
swagger: "2.0"
